
# difficultty of 5% 
# sum = 0
# for i in range(0, 1000):
#     if i % 3 == 0 or i % 5 == 0:
#         sum += i;
# print(f"The sum of list of number below 10 which are mulptiles  = {sum}")


# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
# def Fibonacci(n):
#     if n > 2:
#         return Fibonacci(n - 1) + Fibonacci( n - 2)
#     else:
#         return n + 0

# sum_even_fabo = 0
# for n in range(1, 100):
#     num = Fibonacci(n)
#     if num  > 4000000:
#         break;
#     else:
#         if num % 2 == 0:
#             sum_even_fabo += num
#             print(sum_even_fabo)
     
    # if num % 2 ==0 :
    #     sum_even_fabo += num

        
